name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Rust
      uses: actions-rs/toolchain@v1

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build project
      run: sh build.sh

    - name: Zip artifacts
      run: |
        mkdir dist
        cp left.bin dist/left.bin
        cp right.bin dist/right.bin
        zip -r ${{ github.repository }}.zip dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.repository }}
        path: ${{ github.repository }}.zip
